package com.github.ucchyocean.lunachat.core.network;

public enum FrameType { HELLO, CHALLENGE, AUTHENTICATE, READY, MESSAGE, ACK, HEARTBEAT, STATE, MEMBER_CHANGE, MEMBER_RESULT,
    CHANNEL_CREATE, CHANNEL_CREATE_RESULT,
    PRIVATE_REQUEST, PRIVATE_DELIVERY, PRIVATE_ACK, PRIVATE_RESULT, PRESENCE, PRESENCE_ACK }
